{
 "title": "Demo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "duration_bucket" } }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Latency by Service (from SpanMetrics)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(duration_bucket{service_name=\"${service}\"}[$__rate_interval])) by (le))",
     "legendFormat": "quantile999"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(duration_bucket{service_name=\"${service}\", span_name=~\".*commercetools.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "ct-quantile50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(duration_bucket{service_name=\"${service}\", span_name=~\".*commercetools.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "ct-quantile95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(duration_bucket{service_name=\"${service}\", span_name=~\".*commercetools.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "ct-quantile99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(duration_bucket{service_name=\"${service}\", span_name=~\".*commercetools.*\"}[$__rate_interval])) by (le))",
     "legendFormat": "ct-quantile999"
    }
   ]
  },
  {
   "title": "Error Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(calls{status_code=\"STATUS_CODE_ERROR\", service_name=\"${service}\"}[$__interval])",
     "legendFormat": "{{ span_name }}"
    }
   ]
  },
  {
   "title": "Endpoint Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(span_name) (rate(duration_count{service_name=\"${service}\"}[$__rate_interval]))",
     "legendFormat": "{{ span_name }}"
    }
   ]
  }
 ]
}