# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

exporters:
  otlphttp:
    endpoint: https://your-endpoint.live.dynatrace.com/api/v2/otlp
    headers:
      Authorization: "Api-Token dt0c01.your.key"

service:
  pipelines:
    traces:
      exporters: [otlp, logging, spanmetrics, otlphttp]
    metrics:
      exporters: [prometheus, logging, otlphttp]
    logs:
      exporters: [logging, otlphttp]
