# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  logging:
processors:
  batch:
  cumulativetodelta:
  transform:
    trace_statements:
      - context: span
        statements:
          - delete_key(resource.attributes, "process.command_args")
          - truncate_all(attributes, 4095)
          - truncate_all(resource.attributes, 4095)
    log_statements:
      - context: log
        statements:
          - delete_key(resource.attributes, "process.command_args")
          - truncate_all(attributes, 4095)
          - truncate_all(resource.attributes, 4095)
    metric_statements:
      - context: metric
        statements:
          - delete_key(resource.attributes, "process.command_args")
          - set(description, "Measures the duration of inbound HTTP requests") where name == "http.server.duration"
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize
          - duration
          - http.server.duration
          - http.client.duration
          - process.runtime.jvm.system.cpu.load_1m
          - process.runtime.jvm.gc.duration
          - jvm.gc.pause

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [logging, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [filter, cumulativetodelta, transform, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [transform, batch]
      exporters: [logging]
